title: AQUARIUM-HB
description: "A comprehensive pipeline for identifying, annotating, quantifying, and analyzing human blood circular RNAs from RNA-seq data."  
theme: jekyll-theme-minimal  

# 网站URL  
url: "https://njucmbioinfo.github.io/AQUARIUM-HB/"

# 导航菜单  
navigation:  
  - title: Home  
    url: /  
  - title: Pipeline Overview  
    url: /pipeline  
  - title: Resources  
    url: /resources  
  - title: Contact  
    url: /contact  

